version: 0.2

env:
  variables:
    JAVA_HOME: "java-11-openjdk-11.0.7.10-4.amzn2.0.1.x86_64"

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradlew build
artifacts:
  files:
    - appspec.yml
    - *.sh
    - *.jar
  discard-paths: yes
