name: Deployment build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build  
    - name: Where iam
      run: ls -la
    - name: see it
      run: ls -la build/
    - name: see it
      run: ls -la build/libs/
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with: 
        name: Package
        path: build/libs/task-management-service-0.0.1-SNAPSHOT.jar
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with: 
        name: Package
        path: staging

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync /home/runner/work/Task-management-service/build/libs s3://${{ secrets.AWS_S3_BUCKET }}
    
